### ISSUE TITLE
Safari Bug - Intermittently shows Loading Screen - that’s it. 

### ISSUE THREAD

**Issue by dubenm2012** [Bulbacode/famysh#10]
After hitting the find me some food button the loading screen with the blue circles appeared. But that’s it. Waiting 2 minutes and expanding the mileage range had no effect. Also it never actually asked me for my location at any point. 

I’m using safari from an iPhone.

**Comment by Bulbacode** [comment]
Need to look into possible failure cases for geolocation. This has been an infrequent but repeatable issue. Possibly just logging what’s going on could help us diagnose the issue later.

**Comment by taramcfate** [comment]
mine has been doing the exact same thing it doesn't ask for my location or anything, just a loading screen

**Comment by Bulbacode** [comment]
Closing as this is no longer relevant
