### ISSUE TITLE
Intermittent “in the woods” message from failed api calls? (Lack of options)

### ISSUE THREAD

**Issue by Brookelynn20** [Bulbacode/famysh#14]
It’s only recognizing 2 places in the 20 mile radius of where I live. There are a ton more, so I just wanted to let you know.

**Comment by Bulbacode** [comment]
This is actually a bug with the in the woods message showing up intermittently. It recognizes more resturaunts you just need to restart the search from the beginning. 

I’ll use this issue to track that intermittent woods bug.

**Comment by Bulbacode** [comment]
Closing as no longer relevant
