### ISSUE TITLE
Setting up local dev environment

### ISSUE THREAD

**Issue by Fin413** [Bulbacode/famysh#22]
I'm able to run the frontend using "ng serve" but I can't figure out how to setup the API with it. Right now the site just displays all the components on a single page and isn't functional. New to angular so maybe I'm missing something basic

**Comment by Bulbacode** [comment]
I need to write better docs on it. Give me a couple days and I can resolve this.

**Comment by Bulbacode** [comment]
Closing issue since docs were updated.
