### ISSUE TITLE
Did not recommend a restaurant 

### ISSUE THREAD

**Issue by nicnakk** [Bulbacode/famysh#4]
Hey there,

I love the site but it did not recommend restaurant to me, it recommended a skating rink. 

![1BFAEA83-8600-48E4-8482-E6F9C20D95A4](https://user-images.githubusercontent.com/77948615/105656484-5340f680-5e90-11eb-8fce-5a900a846dfc.png)

**Comment by Bulbacode** [comment]
We'll look into this one. There should be some info in the logs as to why this was recommended.

**Comment by Bulbacode** [comment]
Marking as closed since we switched search providers from google to yelp
