### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by Schuhbauer12** [Bulbacode/famysh#7]
Hi! I live in Canada, in Québec to be exact, and this can only recommend restaurants in Ontario (aka English) for me to go to. I tried running in a smaller radius, but it thinks there are no food places nearby (there's no food in these woods) 😂. If I search for food on Google it does show restaurants on both sides of the border, so it is possible.

**Comment by Bulbacode** [comment]
We've switched search providers from google to yelp, so closing this for now unless it comes back up
